### PR TITLE
Hack in workspaces name.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Okay, this now opens the workspace automatically. It isn't pretty, but works.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
https://mybinder.org/v2/gh/ian-r-rose/dask-examples/jlab?urlpath=lab

**Comment by mrocklin** [comment]
Awesome.  Doing this I definitely get the correct link in the dask JLab extension, which is great.

I'm not yet getting the pane-layout that I was hoping for, but I am being dropped into a particular notebook, which is interesting.  
https://github.com/dask/dask-examples/pull/38/files#diff-41c13456706ac2dad44cc3696c99563b

**Comment by mrocklin** [comment]
I notice that you force pushed.  The change here seems to resolve the problem of the pane layout (which looks and operates great now).  One more question (my apologies for continuing to come back with these) but is it possible to also target a specific notebook?  We have links in our [main docs](https://dask.pydata.org) that point to specific examples for arrays, dataframes, machine learning, etc., and are likely to have more in the future.  Previously we added `?filepath=/path/to/notebook.ipynb` to the end of the URL, which pointed us to a particular notebook.  Now it appears that the workspace seems to take priority over that mechanism.  It seems to me that we might be able to replace the path to the notebook in the workspace with the entry from the `filepath=` bit of the request.  Is there an easy way to do this that you know of?

**Comment by ian-r-rose** [comment]
Yes, I amended the commit.

We can in fact combine workspaces with opening a particular file with the `/tree` handler. So if instead you go to the url `/lab/tree/array.ipynb` it will open `array.ipynb` in that workapce. It has less control over where the opened file is placed, but if you want it in the left pane (as we do now), then it should work fine.

So I would propose we have something like the `README.md` as the default opened file in the workspace, and then we can go to `lab/tree/yournotebook.ipynb`, which will open the desired notebook on top of `README.md`.

**Comment by mrocklin** [comment]
Awesome, so navigating to https://mybinder.org/v2/gh/ian-r-rose/dask-examples/jlab?urlpath=lab/tree/array.ipynb does exactly the right thing.  I agree that having some sort of welcome message as the primary pane and then adding these probably makes sense.  Great.  I think that this is all that we need.  Thanks as always @ian-r-rose !

**Pull request merged**
